/* SPDX-License-Identifier: GPL-2.0-only */

#ifndef CPU_X86_SMM_COMMAND_H
#define CPU_X86_SMM_COMMAND_H

#include <stdbool.h>
#include <types.h>

/* Platform-local definitions audited outside cpu/x86/smm.h. */
#define SMM_APMC_STARLABS_EFI_OPTION 0xe2U
#define SMM_APMC_SPI_CONSOLE 0xe8U
#define SMM_APMC_CAPSULE_BROKER 0xe8U
#define SMM_APMC_ACER_BOARD 0xddU
#define SMM_APMC_AUTHVAR_PRESENCE 0xffU

enum smm_apmc_owner {
	SMM_APMC_OWNER_NONE,
	SMM_APMC_OWNER_ACPI_CONTROL,
	SMM_APMC_OWNER_FINALIZE,
	SMM_APMC_OWNER_XHCI,
	SMM_APMC_OWNER_LEGACY,
	SMM_APMC_OWNER_CFR,
	SMM_APMC_OWNER_OPAL,
	SMM_APMC_OWNER_ROM_ARMOR,
	SMM_APMC_OWNER_SMMINFO,
	SMM_APMC_OWNER_SMMSTORE,
	SMM_APMC_OWNER_ELOG,
	SMM_APMC_OWNER_SPI_CONSOLE,
	SMM_APMC_OWNER_CAPSULE_BROKER,
	SMM_APMC_OWNER_STARLABS_EFI_OPTION,
	SMM_APMC_OWNER_ACER_BOARD,
	SMM_APMC_OWNER_AUTHVAR_PRESENCE,
};

enum smm_apmc_role {
	SMM_APMC_ROLE_NONE,
	SMM_APMC_EXCLUSIVE,
};

/* Values stay reserved even when the corresponding owner is not enabled. */
#define SMM_APMC_RESERVED_COMMANDS(ENTRY) \
	ENTRY(APM_CNT_NOOP_SMI) \
	ENTRY(APM_CNT_ACPI_DISABLE) \
	ENTRY(APM_CNT_ROUTE_ALL_XHCI) \
	ENTRY(APM_CNT_FINALIZE) \
	ENTRY(APM_CNT_LEGACY) \
	ENTRY(APM_CNT_ACPI_ENABLE) \
	ENTRY(SMM_APMC_STARLABS_EFI_OPTION) \
	ENTRY(APM_CNT_CFR_RUNTIME_APPLY) \
	ENTRY(SMM_APMC_SPI_CONSOLE) \
	ENTRY(APM_CNT_OPAL_S3_UNLOCK) \
	ENTRY(APM_CNT_ROM_ARMOR) \
	ENTRY(APM_CNT_MBI_UPDATE) \
	ENTRY(APM_CNT_SMMINFO) \
	ENTRY(APM_CNT_SMMSTORE) \
	ENTRY(APM_CNT_OPAL_SVC) \
	ENTRY(APM_CNT_ELOG_GSMI) \
	ENTRY(SMM_APMC_ACER_BOARD) \
	ENTRY(SMM_APMC_AUTHVAR_PRESENCE)

#if CONFIG(PAYLOAD_SPI_FLASH_CONSOLE)
#define SMM_APMC_SPI_CLAIM(ENTRY) \
	ENTRY(SMM_APMC_SPI_CONSOLE, SMM_APMC_OWNER_SPI_CONSOLE, \
		SMM_APMC_EXCLUSIVE, CONFIG(SMM_APMC_ROUTE_SPI_CONSOLE))
#else
#define SMM_APMC_SPI_CLAIM(ENTRY)
#endif

#if CONFIG(CAPSULE_BROKER_ENDPOINT_PUBLICATION)
#define SMM_APMC_CAPSULE_CLAIM(ENTRY) \
	ENTRY(SMM_APMC_CAPSULE_BROKER, SMM_APMC_OWNER_CAPSULE_BROKER, \
		SMM_APMC_EXCLUSIVE, CONFIG(SMM_APMC_ROUTE_CAPSULE_BROKER))
#else
#define SMM_APMC_CAPSULE_CLAIM(ENTRY)
#endif

#if CONFIG(STARLABS_SMM_OPTION_HANDLER) && \
	CONFIG(STARLABS_ACPI_EFI_OPTION_SMI)
#define SMM_APMC_STARLABS_CLAIM(ENTRY) \
	ENTRY(SMM_APMC_STARLABS_EFI_OPTION, \
		SMM_APMC_OWNER_STARLABS_EFI_OPTION, SMM_APMC_EXCLUSIVE, \
		CONFIG(SMM_APMC_ROUTE_STARLABS_EFI_OPTION))
#else
#define SMM_APMC_STARLABS_CLAIM(ENTRY)
#endif

#if CONFIG(BOARD_ACER_VN7_572G)
#define SMM_APMC_ACER_CLAIM(ENTRY) \
	ENTRY(SMM_APMC_ACER_BOARD, SMM_APMC_OWNER_ACER_BOARD, \
		SMM_APMC_EXCLUSIVE, CONFIG(SMM_APMC_ROUTE_ACER_BOARD))
#else
#define SMM_APMC_ACER_CLAIM(ENTRY)
#endif

#if CONFIG(SMM_APMC_ROUTE_ACPI_CONTROL)
#define SMM_APMC_ACPI_CLAIMS(ENTRY) \
	ENTRY(APM_CNT_ACPI_DISABLE, SMM_APMC_OWNER_ACPI_CONTROL, \
		SMM_APMC_EXCLUSIVE, 1) \
	ENTRY(APM_CNT_ACPI_ENABLE, SMM_APMC_OWNER_ACPI_CONTROL, \
		SMM_APMC_EXCLUSIVE, 1)
#else
#define SMM_APMC_ACPI_CLAIMS(ENTRY)
#endif

#if CONFIG(SMM_APMC_ROUTE_FINALIZE)
#define SMM_APMC_FINALIZE_CLAIM(ENTRY) \
	ENTRY(APM_CNT_FINALIZE, SMM_APMC_OWNER_FINALIZE, \
		SMM_APMC_EXCLUSIVE, 1)
#else
#define SMM_APMC_FINALIZE_CLAIM(ENTRY)
#endif

#define SMM_APMC_LIFECYCLE_CLAIMS(ENTRY) \
	SMM_APMC_ACPI_CLAIMS(ENTRY) \
	SMM_APMC_FINALIZE_CLAIM(ENTRY)

#if CONFIG(SMM_APMC_ROUTE_AUTHVAR_PRESENCE)
#define SMM_APMC_AUTHVAR_PRESENCE_CLAIM(ENTRY) \
	ENTRY(SMM_APMC_AUTHVAR_PRESENCE, SMM_APMC_OWNER_AUTHVAR_PRESENCE, \
		SMM_APMC_EXCLUSIVE, 1)
#else
#define SMM_APMC_AUTHVAR_PRESENCE_CLAIM(ENTRY)
#endif

/* No observer is attested by the currently supported route compositions. */
#define SMM_APMC_ENABLED_OBSERVERS(ENTRY)

#if CONFIG(SMM_APMC_ROUTE_XHCI)
#define SMM_APMC_XHCI_CLAIM(ENTRY) \
	ENTRY(APM_CNT_ROUTE_ALL_XHCI, SMM_APMC_OWNER_XHCI, \
		SMM_APMC_EXCLUSIVE, 1)
#else
#define SMM_APMC_XHCI_CLAIM(ENTRY)
#endif

#if CONFIG(SMM_APMC_ROUTE_LEGACY)
#define SMM_APMC_LEGACY_CLAIM(ENTRY) \
	ENTRY(APM_CNT_LEGACY, SMM_APMC_OWNER_LEGACY, SMM_APMC_EXCLUSIVE, 1)
#else
#define SMM_APMC_LEGACY_CLAIM(ENTRY)
#endif

#if CONFIG(DRIVERS_OPTION_CFR_RUNTIME_APPLY)
#define SMM_APMC_CFR_CLAIM(ENTRY) \
	ENTRY(APM_CNT_CFR_RUNTIME_APPLY, SMM_APMC_OWNER_CFR, \
		SMM_APMC_EXCLUSIVE, CONFIG(SMM_APMC_ROUTE_CFR))
#else
#define SMM_APMC_CFR_CLAIM(ENTRY)
#endif

#if CONFIG(TCG_OPAL_S3_UNLOCK)
#define SMM_APMC_OPAL_CLAIMS(ENTRY) \
	ENTRY(APM_CNT_OPAL_S3_UNLOCK, SMM_APMC_OWNER_OPAL, \
		SMM_APMC_EXCLUSIVE, CONFIG(SMM_APMC_ROUTE_OPAL)) \
	ENTRY(APM_CNT_OPAL_SVC, SMM_APMC_OWNER_OPAL, \
		SMM_APMC_EXCLUSIVE, CONFIG(SMM_APMC_ROUTE_OPAL))
#else
#define SMM_APMC_OPAL_CLAIMS(ENTRY)
#endif

#if CONFIG(SOC_AMD_COMMON_BLOCK_PSP_ROM_ARMOR3)
#define SMM_APMC_ROM_ARMOR_CLAIM(ENTRY) \
	ENTRY(APM_CNT_ROM_ARMOR, SMM_APMC_OWNER_ROM_ARMOR, SMM_APMC_EXCLUSIVE, \
		CONFIG(SMM_APMC_ROUTE_ROM_ARMOR))
#else
#define SMM_APMC_ROM_ARMOR_CLAIM(ENTRY)
#endif

#if CONFIG(SMM_APMC_ROUTE_SMMINFO)
#define SMM_APMC_SMMINFO_CLAIM(ENTRY) \
	ENTRY(APM_CNT_SMMINFO, SMM_APMC_OWNER_SMMINFO, SMM_APMC_EXCLUSIVE, 1)
#else
#define SMM_APMC_SMMINFO_CLAIM(ENTRY)
#endif

#if CONFIG(SMMSTORE)
#define SMM_APMC_SMMSTORE_CLAIM(ENTRY) \
	ENTRY(APM_CNT_SMMSTORE, SMM_APMC_OWNER_SMMSTORE, SMM_APMC_EXCLUSIVE, \
		CONFIG(SMM_APMC_ROUTE_SMMSTORE))
#else
#define SMM_APMC_SMMSTORE_CLAIM(ENTRY)
#endif

#if CONFIG(ELOG_GSMI)
#define SMM_APMC_ELOG_CLAIM(ENTRY) \
	ENTRY(APM_CNT_ELOG_GSMI, SMM_APMC_OWNER_ELOG, SMM_APMC_EXCLUSIVE, \
		CONFIG(SMM_APMC_ROUTE_ELOG))
#else
#define SMM_APMC_ELOG_CLAIM(ENTRY)
#endif

/*
 * This dormant slice records only claims with an audited build-time route.
 * Lifecycle owners and their optional observers are separate. This slice has
 * no attested lifecycle observers. A binding count other than one is never
 * dispatch-ready.
 */
#define SMM_APMC_ENABLED_CLAIMS(ENTRY) \
	SMM_APMC_LIFECYCLE_CLAIMS(ENTRY) \
	SMM_APMC_XHCI_CLAIM(ENTRY) \
	SMM_APMC_LEGACY_CLAIM(ENTRY) \
	SMM_APMC_CFR_CLAIM(ENTRY) \
	SMM_APMC_OPAL_CLAIMS(ENTRY) \
	SMM_APMC_ROM_ARMOR_CLAIM(ENTRY) \
	SMM_APMC_SMMINFO_CLAIM(ENTRY) \
	SMM_APMC_SMMSTORE_CLAIM(ENTRY) \
	SMM_APMC_ELOG_CLAIM(ENTRY) \
	SMM_APMC_SPI_CLAIM(ENTRY) \
	SMM_APMC_CAPSULE_CLAIM(ENTRY) \
	SMM_APMC_AUTHVAR_PRESENCE_CLAIM(ENTRY) \
	SMM_APMC_STARLABS_CLAIM(ENTRY) \
	SMM_APMC_ACER_CLAIM(ENTRY)

struct smm_apmc_descriptor {
	u8 command;
	u8 owner;
	u8 role;
	u8 binding_count;
	u8 observer_count;
	bool reserved;
	bool enabled;
};

#define SMM_APMC_SELECTION_RECEIPT_REVISION 1U
struct smm_apmc_selection_receipt {
	u32 revision;
	u32 size;
	u64 identity;
	u64 generation;
	struct smm_apmc_descriptor descriptor;
	u8 reserved;
} __aligned(8);

_Static_assert(sizeof(struct smm_apmc_selection_receipt) == 32,
	"SMM APMC selection receipt ABI changed");
_Static_assert(_Alignof(struct smm_apmc_selection_receipt) == 8,
	"SMM APMC selection receipt alignment changed");
_Static_assert(offsetof(struct smm_apmc_selection_receipt, identity) == 8,
	"SMM APMC selection receipt identity offset changed");
_Static_assert(offsetof(struct smm_apmc_selection_receipt, generation) == 16,
	"SMM APMC selection receipt generation offset changed");
_Static_assert(offsetof(struct smm_apmc_selection_receipt, descriptor) == 24,
	"SMM APMC selection receipt descriptor offset changed");

enum smm_apmc_select_result {
	SMM_APMC_SELECT_UNKNOWN,
	SMM_APMC_SELECT_CONSUMED_REJECT,
	SMM_APMC_SELECT_ENABLED,
};

enum smm_apmc_dispatch_result {
	SMM_APMC_CONSUMED_SUCCESS,
	SMM_APMC_CONSUMED_REJECT,
};

enum smm_apmc_select_result
smm_apmc_command_select(u8 command,
			struct smm_apmc_selection_receipt *receipt);
enum smm_apmc_dispatch_result
smm_apmc_command_consume(u8 expected_command,
			 enum smm_apmc_owner expected_owner,
			 struct smm_apmc_selection_receipt *receipt);

#endif
