/* SPDX-License-Identifier: GPL-2.0-only */
#ifndef TEST_SMMSTORE_FULL_FLASH_FMAP_CONFIG_H
#define TEST_SMMSTORE_FULL_FLASH_FMAP_CONFIG_H

#define FMAP_SECTION_FLASH_START 0
#define FMAP_SECTION_FLASH_SIZE 0x2000000
#define FMAP_SECTION_SMMSTORE_START 0x760000
#define FMAP_SECTION_SMMSTORE_SIZE 0x80000

#endif
