/* SPDX-License-Identifier: GPL-2.0-only */

#ifndef FMAPTOOL_GENERATED_HEADER_H_
#define FMAPTOOL_GENERATED_HEADER_H_

#define FMAP_SECTION_FLASH_START 0
#define FMAP_SECTION_FLASH_SIZE 0x1000000
#define FMAP_SECTION_SMMSTORE_START 0xd30000
#define FMAP_SECTION_SMMSTORE_SIZE 0x40000

#endif
