/* SPDX-License-Identifier: GPL-2.0-only */

#ifndef TESTS_LIB_FLASHCONSOLE_FMAP_CONFIG_H
#define TESTS_LIB_FLASHCONSOLE_FMAP_CONFIG_H

#define FMAP_SECTION_FLASH_START 0
#define FMAP_SECTION_FLASH_SIZE CONFIG_ROM_SIZE

#endif
