/* SPDX-License-Identifier: GPL-2.0-only */

#ifndef STARLABS_CFR_RUNTIME_H
#define STARLABS_CFR_RUNTIME_H

/* Shared by the CFR records and the touchpad ASL consumer. */
#define STARLABS_CFR_ID_TOUCHPAD_HAPTICS		14
#define STARLABS_CFR_ID_TOUCHPAD_FORCE_PRESS	15
#define STARLABS_CFR_ID_TOUCHPAD_FORCE_RELEASE	16
#define STARLABS_CFR_ID_TOUCHPAD_REPORT_RATE	17

#define STARLABS_CFR_RUNTIME_STATUS_INDEX	0
#define STARLABS_CFR_RUNTIME_VALUE_INDEX	1
#define STARLABS_CFR_RUNTIME_PACKAGE_SIZE	2
#define STARLABS_CFR_RUNTIME_SUCCESS	0
#define STARLABS_CFR_RUNTIME_ERROR	1
#define STARLABS_CFR_RUNTIME_VALUE_NONE	0

#endif
