/* SPDX-License-Identifier: GPL-2.0-only */

#include <common/touchpad.h>
#include <starlabs/cfr_runtime.h>

#define BVAL(buffer, offset) DerefOf (Index (buffer, offset))
#define TP_LO_BYTE(value) ((value) & 0xff)
#define TP_HI_BYTE(value) ((value) >> 8)
#define TP_GSB_STATUS_INDEX 0
#define TP_GSB_COUNT_INDEX 1
#define TP_GSB_SUCCESS 0
#define TP_HID_LENGTH_LO_INDEX 2
#define TP_HID_LENGTH_HI_INDEX 3
#define TP_HID_LENGTH_HI_VALUE 0
#define TP_HID_REPORT_ID_INDEX 4
#define TP_HID_PAYLOAD_INDEX 5
#define TP_HAPTICS_REPORT_LEN 4
#define TP_HAPTICS_VALUE_INDEX TP_HID_PAYLOAD_INDEX
#define TP_FORCE_REPORT_LEN 7
#define TP_FORCE_PRESS_LO_INDEX TP_HID_PAYLOAD_INDEX
#define TP_FORCE_PRESS_HI_INDEX (TP_HID_PAYLOAD_INDEX + 1)
#define TP_FORCE_RELEASE_LO_INDEX (TP_HID_PAYLOAD_INDEX + 2)
#define TP_FORCE_RELEASE_HI_INDEX (TP_HID_PAYLOAD_INDEX + 3)
#define TP_RATE_REPORT_LEN 6
#define TP_RATE_ADDR_INDEX TP_HID_PAYLOAD_INDEX
#define TP_RATE_BANK_INDEX (TP_HID_PAYLOAD_INDEX + 1)
#define TP_RATE_VALUE_INDEX (TP_HID_PAYLOAD_INDEX + 2)
#define TP_GET_HAPTICS_BUFFER_SIZE 8
#define TP_GET_HAPTICS_DATA_LEN 6
#define TP_GET_FORCE_BUFFER_SIZE 9
#define TP_GET_FORCE_DATA_LEN 6
#define TP_GET_RATE_BUFFER_SIZE 9
#define TP_GET_RATE_DATA_LEN 7
#define TP_SET_HAPTICS_BUFFER_SIZE 12
#define TP_SET_HAPTICS_DATA_LEN 10
#define TP_SET_HAPTICS_VALUE_INDEX 11
#define TP_SET_FORCE_BUFFER_SIZE 15
#define TP_SET_FORCE_DATA_LEN 13
#define TP_SET_FORCE_PRESS_LO_INDEX 11
#define TP_SET_FORCE_PRESS_HI_INDEX 12
#define TP_SET_FORCE_RELEASE_LO_INDEX 13
#define TP_SET_FORCE_RELEASE_HI_INDEX 14
#define TP_SET_RATE_BUFFER_SIZE 15
#define TP_SET_RATE_DATA_LEN 13
#define TP_SET_RATE_VALUE_INDEX 14
#define TP_FORCE_PACKAGE_SIZE 3
#define TP_FORCE_RELEASE_VALUE_INDEX 2

Scope (\_SB.PCI0.I2C0)
{
	Name (TCON, ResourceTemplate ()
	{
		I2cSerialBus (STARLABS_TOUCHPAD_I2C_ADDR, ControllerInitiated, 400000,
			AddressingMode7Bit, "\\_SB.PCI0.I2C0")
	})

	OperationRegion (TPOR, GenericSerialBus, Zero, 0x100)

	Field (TPOR, BufferAcc, NoLock, Preserve)
	{
		Connection (TCON),
		AccessAs (BufferAcc, AttribSendReceive),
		WAK0, 8
	}

	Field (TPOR, BufferAcc, NoLock, Preserve)
	{
		Connection (TCON),
		AccessAs (BufferAcc, AttribBytes (TP_SET_HAPTICS_DATA_LEN)),
		Offset (STARLABS_TOUCHPAD_FALLBACK_CMD_REG),
		WHP0, 8
	}

	Field (TPOR, BufferAcc, NoLock, Preserve)
	{
		Connection (TCON),
		AccessAs (BufferAcc, AttribBytes (TP_SET_FORCE_DATA_LEN)),
		Offset (STARLABS_TOUCHPAD_FALLBACK_CMD_REG),
		WFC0, 8
	}

	Field (TPOR, BufferAcc, NoLock, Preserve)
	{
		Connection (TCON),
		AccessAs (BufferAcc, AttribBytes (TP_SET_RATE_DATA_LEN)),
		Offset (STARLABS_TOUCHPAD_FALLBACK_CMD_REG),
		WRT0, 8
	}

	Field (TPOR, BufferAcc, NoLock, Preserve)
	{
		Connection (TCON),
		AccessAs (BufferAcc, AttribRawProcessBytes (TP_HAPTICS_REPORT_LEN)),
		RHP0, 8
	}

	Field (TPOR, BufferAcc, NoLock, Preserve)
	{
		Connection (TCON),
		AccessAs (BufferAcc, AttribRawProcessBytes (TP_FORCE_REPORT_LEN)),
		RFC0, 8
	}

	Field (TPOR, BufferAcc, NoLock, Preserve)
	{
		Connection (TCON),
		AccessAs (BufferAcc, AttribRawProcessBytes (TP_RATE_REPORT_LEN)),
		RRT0, 8
	}

	Method (TPWK, 0, NotSerialized)
	{
		Local0 = WAK0
		Sleep (STARLABS_TOUCHPAD_WAKE_DELAY_MS)
		Return (Local0)
	}

	Method (GHAP, 0, NotSerialized)
	{
		Local0 = Buffer (TP_GET_HAPTICS_BUFFER_SIZE)
		{
			0, TP_GET_HAPTICS_DATA_LEN,
			TP_LO_BYTE (STARLABS_TOUCHPAD_FALLBACK_CMD_REG),
			TP_HI_BYTE (STARLABS_TOUCHPAD_FALLBACK_CMD_REG),
			I2C_HID_FEATURE_REPORT (STARLABS_TOUCHPAD_HAPTICS_REPORT_ID),
			I2C_HID_OPCODE_GET_REPORT,
			TP_LO_BYTE (STARLABS_TOUCHPAD_FALLBACK_DATA_REG),
			TP_HI_BYTE (STARLABS_TOUCHPAD_FALLBACK_DATA_REG)
		}
		Local0 = (RHP0 = Local0)

		If ((BVAL (Local0, TP_GSB_STATUS_INDEX) != TP_GSB_SUCCESS) ||
		    (BVAL (Local0, TP_GSB_COUNT_INDEX) != TP_HAPTICS_REPORT_LEN) ||
		    (BVAL (Local0, TP_HID_LENGTH_LO_INDEX) != TP_HAPTICS_REPORT_LEN) ||
		    (BVAL (Local0, TP_HID_LENGTH_HI_INDEX) != TP_HID_LENGTH_HI_VALUE) ||
		    (BVAL (Local0, TP_HID_REPORT_ID_INDEX) !=
		     STARLABS_TOUCHPAD_HAPTICS_REPORT_ID))
		{
			Return (Package (STARLABS_CFR_RUNTIME_PACKAGE_SIZE)
			{
				STARLABS_CFR_RUNTIME_ERROR,
				STARLABS_CFR_RUNTIME_VALUE_NONE
			})
		}

		Local1 = Package (STARLABS_CFR_RUNTIME_PACKAGE_SIZE)
		{
			STARLABS_CFR_RUNTIME_SUCCESS,
			STARLABS_CFR_RUNTIME_VALUE_NONE
		}
		Local1[STARLABS_CFR_RUNTIME_VALUE_INDEX] = BVAL (Local0, TP_HAPTICS_VALUE_INDEX)
		Return (Local1)
	}

	Method (GFRC, 0, NotSerialized)
	{
		Local0 = Buffer (TP_GET_FORCE_BUFFER_SIZE)
		{
			0, TP_GET_FORCE_DATA_LEN,
			TP_LO_BYTE (STARLABS_TOUCHPAD_FALLBACK_CMD_REG),
			TP_HI_BYTE (STARLABS_TOUCHPAD_FALLBACK_CMD_REG),
			I2C_HID_FEATURE_REPORT (STARLABS_TOUCHPAD_FORCE_REPORT_ID),
			I2C_HID_OPCODE_GET_REPORT,
			TP_LO_BYTE (STARLABS_TOUCHPAD_FALLBACK_DATA_REG),
			TP_HI_BYTE (STARLABS_TOUCHPAD_FALLBACK_DATA_REG),
			0
		}
		Local0 = (RFC0 = Local0)

		If ((BVAL (Local0, TP_GSB_STATUS_INDEX) != TP_GSB_SUCCESS) ||
		    (BVAL (Local0, TP_GSB_COUNT_INDEX) != TP_FORCE_REPORT_LEN) ||
		    (BVAL (Local0, TP_HID_LENGTH_LO_INDEX) != TP_FORCE_REPORT_LEN) ||
		    (BVAL (Local0, TP_HID_LENGTH_HI_INDEX) != TP_HID_LENGTH_HI_VALUE) ||
		    (BVAL (Local0, TP_HID_REPORT_ID_INDEX) !=
		     STARLABS_TOUCHPAD_FORCE_REPORT_ID))
		{
			Return (Package (TP_FORCE_PACKAGE_SIZE)
			{
				STARLABS_CFR_RUNTIME_ERROR,
				STARLABS_CFR_RUNTIME_VALUE_NONE,
				STARLABS_CFR_RUNTIME_VALUE_NONE
			})
		}

		Local1 = BVAL (Local0, TP_FORCE_PRESS_LO_INDEX) |
			(BVAL (Local0, TP_FORCE_PRESS_HI_INDEX) << 8)
		Local2 = BVAL (Local0, TP_FORCE_RELEASE_LO_INDEX) |
			(BVAL (Local0, TP_FORCE_RELEASE_HI_INDEX) << 8)
		Local3 = Package (TP_FORCE_PACKAGE_SIZE)
		{
			STARLABS_CFR_RUNTIME_SUCCESS,
			STARLABS_CFR_RUNTIME_VALUE_NONE,
			STARLABS_CFR_RUNTIME_VALUE_NONE
		}
		Local3[STARLABS_CFR_RUNTIME_VALUE_INDEX] = Local1
		Local3[TP_FORCE_RELEASE_VALUE_INDEX] = Local2
		Return (Local3)
	}

	Method (GRAT, 0, NotSerialized)
	{
		Local0 = Buffer (TP_GET_RATE_BUFFER_SIZE)
		{
			0, TP_GET_RATE_DATA_LEN,
			TP_LO_BYTE (STARLABS_TOUCHPAD_FALLBACK_CMD_REG),
			TP_HI_BYTE (STARLABS_TOUCHPAD_FALLBACK_CMD_REG),
			I2C_HID_FEATURE_REPORT (I2C_HID_REPORT_ID_EXTENDED),
			I2C_HID_OPCODE_GET_REPORT,
			STARLABS_TOUCHPAD_USER_REG_REPORT_ID,
			TP_LO_BYTE (STARLABS_TOUCHPAD_FALLBACK_DATA_REG),
			TP_HI_BYTE (STARLABS_TOUCHPAD_FALLBACK_DATA_REG)
		}
		Local0 = (RRT0 = Local0)

		If ((BVAL (Local0, TP_GSB_STATUS_INDEX) != TP_GSB_SUCCESS) ||
		    (BVAL (Local0, TP_GSB_COUNT_INDEX) != TP_RATE_REPORT_LEN) ||
		    (BVAL (Local0, TP_HID_LENGTH_LO_INDEX) != TP_RATE_REPORT_LEN) ||
		    (BVAL (Local0, TP_HID_LENGTH_HI_INDEX) != TP_HID_LENGTH_HI_VALUE) ||
		    (BVAL (Local0, TP_HID_REPORT_ID_INDEX) !=
		     STARLABS_TOUCHPAD_USER_REG_REPORT_ID) ||
		    (BVAL (Local0, TP_RATE_ADDR_INDEX) != STARLABS_TOUCHPAD_USER_REG_ADDR_RATE) ||
		    (BVAL (Local0, TP_RATE_BANK_INDEX) != STARLABS_TOUCHPAD_USER_REG_BANK))
		{
			Return (Package (STARLABS_CFR_RUNTIME_PACKAGE_SIZE)
			{
				STARLABS_CFR_RUNTIME_ERROR,
				STARLABS_CFR_RUNTIME_VALUE_NONE
			})
		}

		Local1 = Package (STARLABS_CFR_RUNTIME_PACKAGE_SIZE)
		{
			STARLABS_CFR_RUNTIME_SUCCESS,
			STARLABS_CFR_RUNTIME_VALUE_NONE
		}
		Local1[STARLABS_CFR_RUNTIME_VALUE_INDEX] = BVAL (Local0, TP_RATE_VALUE_INDEX)
		Return (Local1)
	}

	Method (VHAP, 1, NotSerialized)
	{
		Return (Arg0 <= STARLABS_TOUCHPAD_HAPTICS_MAX)
	}

	Method (VFRC, 1, NotSerialized)
	{
		Return ((Arg0 == STARLABS_TOUCHPAD_PRESS_FORCE_MINIMAL) ||
			(Arg0 == STARLABS_TOUCHPAD_PRESS_FORCE_LOW) ||
			(Arg0 == STARLABS_TOUCHPAD_PRESS_FORCE_AVERAGE) ||
			(Arg0 == STARLABS_TOUCHPAD_PRESS_FORCE_HIGH) ||
			(Arg0 == STARLABS_TOUCHPAD_PRESS_FORCE_HULK))
	}

	Method (VRAT, 1, NotSerialized)
	{
		Return ((Arg0 == STARLABS_TOUCHPAD_RATE_RELAXED) ||
			(Arg0 == STARLABS_TOUCHPAD_RATE_BALANCED) ||
			(Arg0 == STARLABS_TOUCHPAD_RATE_FAST) ||
			(Arg0 == STARLABS_TOUCHPAD_RATE_LUDICROUS) ||
			(Arg0 == STARLABS_TOUCHPAD_RATE_PLAID))
	}

	Method (SHAP, 1, NotSerialized)
	{
		If (!VHAP (Arg0))
		{
			Return (STARLABS_CFR_RUNTIME_ERROR)
		}

		TPWK ()
		Local1 = 0
		While (Local1 < STARLABS_TOUCHPAD_RETRIES)
		{
			Local0 = Buffer (TP_SET_HAPTICS_BUFFER_SIZE)
			{
				0, TP_SET_HAPTICS_DATA_LEN,
				TP_LO_BYTE (STARLABS_TOUCHPAD_FALLBACK_CMD_REG),
				TP_HI_BYTE (STARLABS_TOUCHPAD_FALLBACK_CMD_REG),
				I2C_HID_FEATURE_REPORT (STARLABS_TOUCHPAD_HAPTICS_REPORT_ID),
				I2C_HID_OPCODE_SET_REPORT,
				TP_LO_BYTE (STARLABS_TOUCHPAD_FALLBACK_DATA_REG),
				TP_HI_BYTE (STARLABS_TOUCHPAD_FALLBACK_DATA_REG),
				TP_HAPTICS_REPORT_LEN, 0,
				STARLABS_TOUCHPAD_HAPTICS_REPORT_ID,
				0
			}
			Local0[TP_SET_HAPTICS_VALUE_INDEX] = Arg0
			Local0 = (WHP0 = Local0)
			If (BVAL (Local0, TP_GSB_STATUS_INDEX) == TP_GSB_SUCCESS)
			{
				Local2 = 0
				While (Local2 < STARLABS_TOUCHPAD_VERIFY_RETRIES)
				{
					Local3 = GHAP ()
					If ((BVAL (Local3, STARLABS_CFR_RUNTIME_STATUS_INDEX) ==
					     STARLABS_CFR_RUNTIME_SUCCESS) &&
					    (BVAL (Local3, STARLABS_CFR_RUNTIME_VALUE_INDEX) ==
					     Arg0))
					{
						Return (STARLABS_CFR_RUNTIME_SUCCESS)
					}
					Sleep (STARLABS_TOUCHPAD_VERIFY_DELAY_MS)
					Local2++
				}
			}
			Sleep (STARLABS_TOUCHPAD_RETRY_DELAY_MS)
			Local1++
		}

		Return (STARLABS_CFR_RUNTIME_ERROR)
	}

	Method (SFRC, 2, NotSerialized)
	{
		If (!VFRC (Arg0) || !VFRC (Arg1))
		{
			Return (STARLABS_CFR_RUNTIME_ERROR)
		}

		TPWK ()
		Local1 = 0
		While (Local1 < STARLABS_TOUCHPAD_RETRIES)
		{
			Local0 = Buffer (TP_SET_FORCE_BUFFER_SIZE)
			{
				0, TP_SET_FORCE_DATA_LEN,
				TP_LO_BYTE (STARLABS_TOUCHPAD_FALLBACK_CMD_REG),
				TP_HI_BYTE (STARLABS_TOUCHPAD_FALLBACK_CMD_REG),
				I2C_HID_FEATURE_REPORT (STARLABS_TOUCHPAD_FORCE_REPORT_ID),
				I2C_HID_OPCODE_SET_REPORT,
				TP_LO_BYTE (STARLABS_TOUCHPAD_FALLBACK_DATA_REG),
				TP_HI_BYTE (STARLABS_TOUCHPAD_FALLBACK_DATA_REG),
				TP_FORCE_REPORT_LEN, 0,
				STARLABS_TOUCHPAD_FORCE_REPORT_ID,
				0, 0, 0, 0
			}
			Local0[TP_SET_FORCE_PRESS_LO_INDEX] = Arg0
			Local0[TP_SET_FORCE_PRESS_HI_INDEX] = Arg0 >> 8
			Local0[TP_SET_FORCE_RELEASE_LO_INDEX] = Arg1
			Local0[TP_SET_FORCE_RELEASE_HI_INDEX] = Arg1 >> 8
			Local0 = (WFC0 = Local0)
			If (BVAL (Local0, TP_GSB_STATUS_INDEX) == TP_GSB_SUCCESS)
			{
				Local2 = 0
				While (Local2 < STARLABS_TOUCHPAD_VERIFY_RETRIES)
				{
					Local3 = GFRC ()
					If ((BVAL (Local3, STARLABS_CFR_RUNTIME_STATUS_INDEX) ==
					     STARLABS_CFR_RUNTIME_SUCCESS) &&
					    (BVAL (Local3, STARLABS_CFR_RUNTIME_VALUE_INDEX) ==
					     Arg0) &&
					    (BVAL (Local3, TP_FORCE_RELEASE_VALUE_INDEX) == Arg1))
					{
						Return (STARLABS_CFR_RUNTIME_SUCCESS)
					}
					Sleep (STARLABS_TOUCHPAD_VERIFY_DELAY_MS)
					Local2++
				}
			}
			Sleep (STARLABS_TOUCHPAD_RETRY_DELAY_MS)
			Local1++
		}

		Return (STARLABS_CFR_RUNTIME_ERROR)
	}

	Method (SRAT, 1, NotSerialized)
	{
		If (!VRAT (Arg0))
		{
			Return (STARLABS_CFR_RUNTIME_ERROR)
		}

		TPWK ()
		Local1 = 0
		While (Local1 < STARLABS_TOUCHPAD_RETRIES)
		{
			Local0 = Buffer (TP_SET_RATE_BUFFER_SIZE)
			{
				0, TP_SET_RATE_DATA_LEN,
				TP_LO_BYTE (STARLABS_TOUCHPAD_FALLBACK_CMD_REG),
				TP_HI_BYTE (STARLABS_TOUCHPAD_FALLBACK_CMD_REG),
				I2C_HID_FEATURE_REPORT (I2C_HID_REPORT_ID_EXTENDED),
				I2C_HID_OPCODE_SET_REPORT,
				STARLABS_TOUCHPAD_USER_REG_REPORT_ID,
				TP_LO_BYTE (STARLABS_TOUCHPAD_FALLBACK_DATA_REG),
				TP_HI_BYTE (STARLABS_TOUCHPAD_FALLBACK_DATA_REG),
				TP_RATE_REPORT_LEN, 0,
				STARLABS_TOUCHPAD_USER_REG_REPORT_ID,
				STARLABS_TOUCHPAD_USER_REG_ADDR_RATE,
				0
			}
			Local0[TP_SET_RATE_VALUE_INDEX] = Arg0
			Local0 = (WRT0 = Local0)
			If (BVAL (Local0, TP_GSB_STATUS_INDEX) == TP_GSB_SUCCESS)
			{
				Local2 = 0
				While (Local2 < STARLABS_TOUCHPAD_VERIFY_RETRIES)
				{
					Local3 = GRAT ()
					If ((BVAL (Local3, STARLABS_CFR_RUNTIME_STATUS_INDEX) ==
					     STARLABS_CFR_RUNTIME_SUCCESS) &&
					    (BVAL (Local3, STARLABS_CFR_RUNTIME_VALUE_INDEX) ==
					     Arg0))
					{
						Return (STARLABS_CFR_RUNTIME_SUCCESS)
					}
					Sleep (STARLABS_TOUCHPAD_VERIFY_DELAY_MS)
					Local2++
				}
			}
			Sleep (STARLABS_TOUCHPAD_RETRY_DELAY_MS)
			Local1++
		}

		Return (STARLABS_CFR_RUNTIME_ERROR)
	}

	Method (TPAP, 2, Serialized)
	{
		If (Arg0 == STARLABS_CFR_ID_TOUCHPAD_HAPTICS)
		{
			Return (SHAP (Arg1))
		}

		If ((Arg0 == STARLABS_CFR_ID_TOUCHPAD_FORCE_PRESS) ||
		    (Arg0 == STARLABS_CFR_ID_TOUCHPAD_FORCE_RELEASE))
		{
			TPWK ()
			Local0 = GFRC ()
			If (BVAL (Local0, STARLABS_CFR_RUNTIME_STATUS_INDEX) !=
			    STARLABS_CFR_RUNTIME_SUCCESS)
			{
				Return (STARLABS_CFR_RUNTIME_ERROR)
			}
			If (Arg0 == STARLABS_CFR_ID_TOUCHPAD_FORCE_PRESS)
			{
				Return (SFRC (Arg1, BVAL (Local0, TP_FORCE_RELEASE_VALUE_INDEX)))
			}
			Return (SFRC (BVAL (Local0, STARLABS_CFR_RUNTIME_VALUE_INDEX), Arg1))
		}

		If (Arg0 == STARLABS_CFR_ID_TOUCHPAD_REPORT_RATE)
		{
			Return (SRAT (Arg1))
		}

		Return (STARLABS_CFR_RUNTIME_ERROR)
	}

	Method (TPGT, 1, Serialized)
	{
		If (Arg0 == STARLABS_CFR_ID_TOUCHPAD_HAPTICS)
		{
			TPWK ()
			Return (GHAP ())
		}

		If ((Arg0 == STARLABS_CFR_ID_TOUCHPAD_FORCE_PRESS) ||
		    (Arg0 == STARLABS_CFR_ID_TOUCHPAD_FORCE_RELEASE))
		{
			TPWK ()
			Local0 = GFRC ()
			If (Arg0 == STARLABS_CFR_ID_TOUCHPAD_FORCE_PRESS)
			{
				Local1 = Package (STARLABS_CFR_RUNTIME_PACKAGE_SIZE)
				{
					STARLABS_CFR_RUNTIME_SUCCESS,
					STARLABS_CFR_RUNTIME_VALUE_NONE
				}
				Local1[STARLABS_CFR_RUNTIME_STATUS_INDEX] =
					BVAL (Local0, STARLABS_CFR_RUNTIME_STATUS_INDEX)
				Local1[STARLABS_CFR_RUNTIME_VALUE_INDEX] =
					BVAL (Local0, STARLABS_CFR_RUNTIME_VALUE_INDEX)
				Return (Local1)
			}
			Local1 = Package (STARLABS_CFR_RUNTIME_PACKAGE_SIZE)
			{
				STARLABS_CFR_RUNTIME_SUCCESS,
				STARLABS_CFR_RUNTIME_VALUE_NONE
			}
			Local1[STARLABS_CFR_RUNTIME_STATUS_INDEX] =
				BVAL (Local0, STARLABS_CFR_RUNTIME_STATUS_INDEX)
			Local1[STARLABS_CFR_RUNTIME_VALUE_INDEX] =
				BVAL (Local0, TP_FORCE_RELEASE_VALUE_INDEX)
			Return (Local1)
		}

		If (Arg0 == STARLABS_CFR_ID_TOUCHPAD_REPORT_RATE)
		{
			TPWK ()
			Return (GRAT ())
		}

		Return (Package (STARLABS_CFR_RUNTIME_PACKAGE_SIZE)
		{
			STARLABS_CFR_RUNTIME_ERROR,
			STARLABS_CFR_RUNTIME_VALUE_NONE
		})
	}
}
