/* SPDX-License-Identifier: GPL-2.0-only */

#include <variants.h>

/* Early pad configuration in bootblock */
const struct pad_config early_gpio_table[] = {
	/* H10:	UART0 RXD			*/
	PAD_CFG_NF(GPP_H08, NONE, DEEP, NF1),
	/* H11:	UART0 TXD			*/
	PAD_CFG_NF(GPP_H09, NONE, DEEP, NF1),

	/* C00:	SMB_CLK				*/
	PAD_CFG_NF(GPP_C00, NONE, DEEP, NF1),
	/* C01:	SMB_DATA			*/
        PAD_CFG_NF(GPP_C01, NONE, DEEP, NF1),
};

const struct pad_config *variant_early_gpio_table(size_t *num)
{
	*num = ARRAY_SIZE(early_gpio_table);
	return early_gpio_table;
}

/* Pad configuration in ramstage. */
const struct pad_config gpio_table[] = {
	/* A00:	ESPI_IO0_EC_R			*/
	PAD_CFG_NF(GPP_A00, UP_20K, DEEP, NF1),
	/* A01:	ESPI_IO1_EC_R			*/
	PAD_CFG_NF(GPP_A01, UP_20K, DEEP, NF1),
	/* A02:	ESPI_IO2_EC_R			*/
	PAD_CFG_NF(GPP_A02, UP_20K, DEEP, NF1),
	/* A03:	ESPI_IO3_EC_R			*/
	PAD_CFG_NF(GPP_A03, UP_20K, DEEP, NF1),
	/* A04:	ESPI_CS0_N			*/
	PAD_CFG_NF(GPP_A04, UP_20K, DEEP, NF1),
	/* A05:	ESPI_CLK_EC_R			*/
	PAD_CFG_NF(GPP_A05, UP_20K, DEEP, NF1),
	/* A06:	ESPI_RESET_N			*/
	PAD_CFG_NF(GPP_A06, NONE, DEEP, NF1),
	/* A12:	WLAN_PEWAKE			*/
	PAD_CFG_GPI(GPP_A12, NONE, DEEP),
	/* A20:	M.2_CPU_SSD_RESET_N		*/
	PAD_CFG_GPO(GPP_A20, 1, PLTRST),
	/* A21:	I2C_PMC_PD_INT_N		*/
	PAD_CFG_NF(GPP_A21, NONE, DEEP, NF1),

	/* B00:	TCHPAD_INT_N			*/
	PAD_CFG_GPI_APIC_LOW(GPP_B00, NONE, PLTRST),
	/* B04:	REBOOT CONTROL
	 *		HIGH:	NO REBOOT
	 *		LOW:	REBOOT ENABLED
	 *		WEAK INTERNAL PD 20K
	 */
	PAD_CFG_GPO(GPP_B04, 0, DEEP),
	/* B13:	PLT_RST_N			*/
	PAD_CFG_NF(GPP_B13, NONE, DEEP, NF1),
	/* B16:	DDIB_DP_HPD			*/
	PAD_CFG_NF(GPP_B16, NONE, DEEP, NF1),
	/* B18:	BT_RF_KILL_N			*/
	PAD_CFG_GPO(GPP_B18, 1, DEEP),
	/* B19:	WIFI_RF_KILL_N			*/
	PAD_CFG_GPO(GPP_B19, 1, DEEP),

	/* C02:	TLS CONFIDENTIALITY
	 *		HIGH:	ENABLED
	 *		LOW:	DISABLED
	 *		WEAK INTERNAL PD 20K	*/
	PAD_CFG_GPO(GPP_C02, 1, DEEP),
	/* C03:	SML0_CLK			*/
	PAD_CFG_NF(GPP_C03, NONE, DEEP, NF1),
	/* C04:	SML0_DATA			*/
	PAD_CFG_NF(GPP_C04, NONE, DEEP, NF1),
	/* C05:	ESPI
	 *		HIGH:	ENABLED
	 *		LOW:	DISABLED
	 *		WEAK INTERNAL PD 20K	*/
	PAD_CFG_GPO(GPP_C05, 1, DEEP),
	/* C06:	SML1_CLK_USBC_PD_N		*/
	PAD_CFG_NF(GPP_C06, NONE, DEEP, NF1),
	/* C07:	SML1_DATA_USBC_PD_N		*/
	PAD_CFG_NF(GPP_C07, NONE, DEEP, NF1),
	/* C08:	SML1ALERT			*/
	/* C12:	CLKREQ3				*/
	/* C15:	RESERVED
	 *		WEAK INTERNAL PD 20K	*/

	/* D06:	SML0BALERT#			*/
	/* D10:	HDA_CODEC_BCLK			*/
	PAD_CFG_NF(GPP_D10, NATIVE, DEEP, NF1),
	/* D11:	HDA_CODEC_SYNC			*/
	PAD_CFG_NF(GPP_D11, NATIVE, DEEP, NF1),
	/* D12:	HDA_CODEC_SDO			*/
	PAD_CFG_NF(GPP_D12, NATIVE, DEEP, NF1),
	/* D13:	HDA_CODEC_SDI			*/
	PAD_CFG_NF(GPP_D13, NATIVE, DEEP, NF1),
	/* D17:	HDA_CODEC_RESET0_N		*/
	PAD_CFG_NF(GPP_D17, NATIVE, DEEP, NF1),
	/* D20: CLKREQ8
	 *			SSD		*/
	PAD_CFG_NF(GPP_D20, NONE, DEEP, NF1),
	/* D21:	CLKREQ5
	 *			WLAN		*/
	PAD_CFG_NF(GPP_D21, NONE, DEEP, NF1),

	/* E04:	M.2_SSD_DEVSLP0			*/
	/* E06:	JTAG ODT
	 *		HIGH:	ENABLED
	 *		LOW:	DISABLED
	 *		20K INTERNAL PU		*/
	/* E09:	USB2_OC0			*/
	/* E14:	EDP_HPD_N			*/
	PAD_CFG_NF(GPP_E14, NONE, DEEP, NF1),
	/* E15:	BOOTHALT_N			*/
	/* E16:	BC_PROCHOT_N			*/
	PAD_CFG_GPI_SCI(GPP_E16, NONE, PLTRST, EDGE_SINGLE, INVERT),
	/* F00:	CNV_BRI_DT			*/
	PAD_CFG_NF(GPP_F00, NONE, DEEP, NF1),
	/* F01:	CNV_BRI_RSP			*/
	PAD_CFG_NF(GPP_F01, UP_20K, DEEP, NF1),
	/* F02:	CNV_RGI_DT			*/
	PAD_CFG_NF(GPP_F02, NONE, DEEP, NF1),
	/* F03:	CNV_RGI_RSP			*/
	PAD_CFG_NF(GPP_F03, UP_20K, DEEP, NF1),
	/* F04:	CNVI_RF_RESET_N			*/
	PAD_CFG_NF(GPP_F00, NONE, DEEP, NF1),
	/* F05:	MODEM_CLKREQ			*/
	PAD_CFG_NF(GPP_F00, NONE, DEEP, NF3),
	/* F10:	SATAXPCIE_1_SATAGP_1		*/
	/* F13:	TPM_IRQ				*/
	/* F19:	ESPI FLASH SHARING
	 *		HIGH:	MASTER
	 *		LOW:	SLAVE
	 *		WEAK INTERNAL PD 20K	*/
	/* F20:	SVID
	 *		HIGH:	PRESENT
	 *		LOW:	NOT PRESENT
	 *		WEAK INTERNAL PD 20K	*/
	/* F21:	CCD
	 *		HIGH:	BALTIC PEAK
	 *		LOW:	BSSB-LS
	 *		WEAK INTERNAL PU 20K	*/

	/* H00:	M.2_PCH_SSD_RESET_N		*/
	PAD_CFG_GPO(GPP_H00, 1, PLTRST),
	/* H01:	FLASH RECOVERY
	 *		HIGH:	ENABLED
	 *		LOW:	DISABLED
	 *		WEAK INTERNAL PD 20K	*/
	/* H02:	WLAN_RST_N			*/
	PAD_CFG_GPO(GPP_H02, 1, PLTRST),
	/* H07:	M.2_CPU_SSD_PWREN		*/
	PAD_CFG_GPO(GPP_H07, 1, PLTRST),
	/* H13:	CPU_C10_GATE_N_R		*/
	PAD_CFG_NF(GPP_H13, NONE, DEEP, NF1),
	/* H16:	DDPB_CTRLCLK			*/
	PAD_CFG_NF(GPP_H16, NONE, DEEP, NF1),
	/* H17:	DDPB_CTRLDATA			*/
	PAD_CFG_NF(GPP_H17, NONE, DEEP, NF1),
	/* H19:	TCHPAD_I2C0_SDA_N		*/
	PAD_CFG_NF(GPP_H19, NONE, DEEP, NF1),
	/* H20:	TCHPAD_I2C0_SCL_N		*/
	PAD_CFG_NF(GPP_H20, NONE, DEEP, NF1),

	/* V00:	PM_BATLOW_N			*/
	PAD_CFG_NF(GPP_V00, NONE, DEEP, NF1),
	/* V01:	CHG_ACOK			*/
	PAD_CFG_NF(GPP_V01, NONE, DEEP, NF1),
	/* V03:	EC_PWRBTN_N			*/
	PAD_CFG_NF(GPP_V03, UP_20K, DEEP, NF1),
	/* V04:	PM_SLP_S3_N			*/
	PAD_CFG_NF(GPP_V04, NONE, DEEP, NF1),
	/* V08:	M.2_BTWIFI_SUS_CLK		*/
	PAD_CFG_NF(GPP_V08, NONE, DEEP, NF1),
	/* V14:	WAKE_N				*/
	PAD_CFG_NF(GPP_V14, NONE, DEEP, NF1),
};

const struct pad_config *variant_gpio_table(size_t *num)
{
	*num = ARRAY_SIZE(gpio_table);
	return gpio_table;
}
